server:
  port: 8087

spring:
  datasource:
    url: jdbc:mariadb://10.1.4.106:3306/recipe_recommendation
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer
  mvc:
    view:
      prefix: /WEB-INF/views/board/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
  file:
    upload:
      location: C:\eGovFrameDev-3.10.0-64bit\workspace2\rest_sample\src\main\webapp\resources\images\
      